--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TPEimperialPE/LibSkinUtils
build-by-default: true
branches:
- main
projects:
  LibSkinUtils:
    path: ""
    model: virion
    type: library
...
